# -*- coding: utf-8 -*-
"""PCA_Olivetti.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O8lqpUEvzKl1tODxv_XiPLJHrcq_K2KM
"""

from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

oliv=datasets.fetch_olivetti_faces()

oliv.keys()

fig=plt.figure(figsize=(8,8))
for i in range(64):
  ax=fig.add_subplot(8,8,i+1)
  ax.imshow(oliv.images[i])
plt.show()

x=oliv.data
y=oliv.target

pca=PCA()
pca.fit(x)

pca.explained_variance_.shape

pca=PCA(n_components=123,whiten=True)
transformed_data=pca.fit_transform(x)
transformed_data.shape

eigenvec=pca.components_
eigenvec.shape

eigenfaces=eigenvec.reshape((123,64,64))

fig=plt.figure(figsize=(8,8))
for i in range(64):
  ax=fig.add_subplot(8,8,i+1)
  ax.imshow(eigenfaces[i])
plt.show()